# MPLAB IDE generated this makefile for use with GNU make.
# Project: EDU05_open_source.mcp
# Date: Sat Nov 23 23:09:51 2013

AS = MPASMWIN.exe
CC = mcc18.exe
LD = mplink.exe
AR = mplib.exe
RM = rm

EDU05_open_source.cof : main.o TimeDelay.o usb_descriptors.o timer.o usb_device.o usb_function_hid.o edu05.o
	$(LD) /p18F24J50 /l"C:\Program Files (x86)\Microchip\mplabc18\v3.45\lib" "rm18f24j50_g.lkr" "main.o" "TimeDelay.o" "usb_descriptors.o" "timer.o" "usb_device.o" "usb_function_hid.o" "edu05.o" /u_CRUNTIME /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"EDU05_open_source.cof" /M"EDU05_open_source.map" /W

main.o : main.c ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/stdio.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/stdlib.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/string.h USB/usb_common.h USB/usb_device.h USB/usb_hal.h TimeDelay.h edu05.h main.c USB/usb.h GenericTypeDefs.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/stddef.h Compiler.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/p18cxxx.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/p18f24j50.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/stdarg.h USB/usb_config.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/limits.h USB/usb_ch9.h USB/usb_hal_pic18.h HardwareProfile.h HardwareProfile\ -\ PIC18F24J50\ PIM.h USB/usb_function_hid.h
	$(CC) -p=18F24J50 /i"C:\Program Files (x86)\Microchip\mplabc18\v3.45\h" "main.c" -fo="main.o" -D__DEBUG -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

TimeDelay.o : TimeDelay.c ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/stdio.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/stdlib.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/string.h TimeDelay.h TimeDelay.c Compiler.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/p18cxxx.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/p18f24j50.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/stdarg.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/stddef.h HardwareProfile.h HardwareProfile\ -\ PIC18F24J50\ PIM.h GenericTypeDefs.h
	$(CC) -p=18F24J50 /i"C:\Program Files (x86)\Microchip\mplabc18\v3.45\h" "TimeDelay.c" -fo="TimeDelay.o" -D__DEBUG -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

usb_descriptors.o : USB/usb_descriptors.c ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/stdio.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/stdlib.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/string.h USB/usb_common.h USB/usb_device.h USB/usb_hal.h USB/usb_descriptors.c USB/usb.h GenericTypeDefs.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/stddef.h Compiler.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/p18cxxx.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/p18f24j50.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/stdarg.h USB/usb_config.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/limits.h USB/usb_ch9.h USB/usb_hal_pic18.h USB/usb_function_hid.h
	$(CC) -p=18F24J50 /i"C:\Program Files (x86)\Microchip\mplabc18\v3.45\h" "USB\usb_descriptors.c" -fo="usb_descriptors.o" -D__DEBUG -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

timer.o : timer.c ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/stdio.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/stdlib.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/string.h Compiler.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/p18cxxx.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/p18f24j50.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/stdarg.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/stddef.h timer.h GenericTypeDefs.h HardwareProfile.h HardwareProfile\ -\ PIC18F24J50\ PIM.h
	$(CC) -p=18F24J50 /i"C:\Program Files (x86)\Microchip\mplabc18\v3.45\h" "timer.c" -fo="timer.o" -D__DEBUG -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

usb_device.o : USB/usb_device.c ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/stdio.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/stdlib.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/string.h USB/usb_common.h USB/usb_device.h USB/usb_hal.h USB/usb_device.c USB/usb.h GenericTypeDefs.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/stddef.h Compiler.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/p18cxxx.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/p18f24j50.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/stdarg.h USB/usb_config.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/limits.h USB/usb_ch9.h USB/usb_hal_pic18.h HardwareProfile.h HardwareProfile\ -\ PIC18F24J50\ PIM.h USB/usb_device_local.h
	$(CC) -p=18F24J50 /i"C:\Program Files (x86)\Microchip\mplabc18\v3.45\h" "USB\usb_device.c" -fo="usb_device.o" -D__DEBUG -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

usb_function_hid.o : USB/usb_function_hid.c ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/stdio.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/stdlib.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/string.h USB/usb_common.h USB/usb_device.h USB/usb_hal.h USB/usb_function_hid.c GenericTypeDefs.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/stddef.h Compiler.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/p18cxxx.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/p18f24j50.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/stdarg.h USB/usb.h USB/usb_config.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/limits.h USB/usb_ch9.h USB/usb_hal_pic18.h USB/usb_function_hid.h
	$(CC) -p=18F24J50 /i"C:\Program Files (x86)\Microchip\mplabc18\v3.45\h" "USB\usb_function_hid.c" -fo="usb_function_hid.o" -D__DEBUG -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

edu05.o : edu05.c edu05.h TimeDelay.h edu05.c p18f24j50.h GenericTypeDefs.h ../Program\ Files\ (x86)/Microchip/mplabc18/v3.45/h/stddef.h
	$(CC) -p=18F24J50 /i"C:\Program Files (x86)\Microchip\mplabc18\v3.45\h" "edu05.c" -fo="edu05.o" -D__DEBUG -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

clean : 
	$(RM) "main.o" "TimeDelay.o" "usb_descriptors.o" "timer.o" "usb_device.o" "usb_function_hid.o" "edu05.o" "EDU05_open_source.cof" "EDU05_open_source.hex"

